CREATE TABLE [dbo].[Empresa]
(
	IdEmpresa INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Empresa PRIMARY KEY CLUSTERED(IdEmpresa)
	, NombreEmpresa VARCHAR(50) NOT NULL
	, Estado BIT NOT NULL CONSTRAINT DF_Empresa_Estado DEFAULT(0)
) WITH (DATA_COMPRESSION = PAGE)
